version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: debt_apps
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - type: bind
        source: ./database/schema.sql
        target: /docker-entrypoint-initdb.d/01-schema.sql
        read_only: true
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - debt-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"
    depends_on:
      - db
    networks:
      - debt-network

  app:
    container_name: debt_apps_php
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - debt-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: debt_apps
      DB_USERNAME: mysql
      DB_PASSWORD: mysql

networks:
  debt-network:
    driver: bridge

volumes:
  mysql_data:
