version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debt-app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - debt-network
    environment:
      DB_HOST: db
      DB_DATABASE: rc126893_mydebts
      DB_USERNAME: rc126893_mydebts
      DB_PASSWORD: Malaysia@2413

  db:
    image: mysql:8.0
    container_name: debt-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Malaysia@2413
      MYSQL_DATABASE: rc126893_mydebts
      MYSQL_USER: rc126893_mydebts
      MYSQL_PASSWORD: Malaysia@2413
      MYSQL_ROOT_HOST: '%'  # Allow root access from any host
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init-permissions.sql:/docker-entrypoint-initdb.d/01-init-permissions.sql
      - ./database/rc126893_mydebts.sql:/docker-entrypoint-initdb.d/02-init-database.sql
    networks:
      - debt-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: debt-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Malaysia@2413
      PMA_USER: rc126893_mydebts
      PMA_PASSWORD: Malaysia@2413
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - debt-network

networks:
  debt-network:
    driver: bridge

volumes:
  dbdata:
