version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: debt_apps
    volumes:
      - type: bind
        source: ./database/init-permissions.sql
        target: /docker-entrypoint-initdb.d/01-init-permissions.sql
        read_only: true
      - type: bind
        source: ./database/3099-db.sql
        target: /docker-entrypoint-initdb.d/02-3099-db.sql
        read_only: true
    ports:
      - "5432:5432"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 5432
      POSTGRES_DB: debt_apps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debt-app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - debt-network
    environment:
      DB_HOST: db
      DB_DATABASE: rc126893_mydebts

networks:
  debt-network:
    driver: bridge
