version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: debt_apps
    volumes:
      - type: bind
        source: ./database/init-permissions.sql
        target: /docker-entrypoint-initdb.d/01-init-permissions.sql
        read_only: true
      - type: bind
        source: ./database/3099-db.sql
        target: /docker-entrypoint-initdb.d/02-3099-db.sql
        read_only: true
    ports:
      - "5432:5432"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 5432
      POSTGRES_DB: debt_apps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - db
